import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./organisms/Header";

// import Swiper styles
import 'swiper/css';
import Footer from "./website/webComponents/Footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navBarItems = [
    { label: "Home", href: "/" },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header logoSrc="/" navBarItems={navBarItems} />

        {children}

        <Footer
          imageSrc="/images/logo.svg"
          decsription="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
          socialLinks={[
            {
              icon: "/images/facebook.svg",
              link: "https://www.facebook.com",
            },
            {
              icon: "/images/twitter.svg",
              link: "https://www.twitter.com",
            },
            {
              icon: "/images/instagram.svg",
              link: "https://www.instagram.com",
            },
          ]}
          topLinks={[
            {
              name: "Privacy Policy",
              link: "/privacy-policy",
            },
            {
              name: "Terms of Service",
              link: "/terms-of-service",
            },
          ]}
          bottomLinks={[
            {
              name: "© 2023 Your Company",
              link: "/",
            },
            {
              name: "All rights reserved.",
              link: "/",
            },
          ]}
        />
     </body>
    </html>
  );
}
